### ISSUE TITLE
How to create such a dump

### ISSUE THREAD

**Issue by bs-matil** [SecurityRAT/Security-Requirements#1]
Hi,
i want to create a similar dump for my own set. Is the creation of this dump documented?

**Comment by AresSec** [comment]
Hi @bs-matil ,

we create our dumps usually with plain mysql-dump and omit the user tables:

`mysqldump -p -u $DBUser --ignore-table={$DB.JHI_AUTHORITY,$DB.JHI_PERSISTENT_AUDIT_EVENT,$DB.JHI_PERSISTENT_AUDIT_EVT_DATA,$DB.JHI_PERSISTENT_TOKEN,$DB.JHI_USER,$DB.JHI_USER_AUTHORITY} $DB> dump.sql`
