### ISSUE TITLE
ASVS version 4?

### ISSUE THREAD

**Issue by didadida5555** [SecurityRAT/Security-Requirements#2]
Hiya, is this going to be updated to match ASVS v4?

**Comment by AresSec** [comment]
Hi @didadida5555 ,

yes I'll update the requirement shortly to match the new ASVS v4. I think something about two weeks until I'll publish it.
Ares

**Comment by vikasprogrammer** [comment]
Any updates on v4? 

PS: There is a v2 of Security RAT repo, but I am not sure what that is. Which one should we use?

**Comment by AresSec** [comment]
Hi @didadida5555 and @vikasprogrammer,
I'm still on creating the ASVS requirement set. I'll close the ticket here when it's finish, so you get a notification when its done.

SecurityRAT V2 repo ist for SecurityRAT version 2 and currently is in developemt. I would not recommend using it for production. Just stick with the normal SecurityRAT repo.

**Comment by AresSec** [comment]
Thanks to @masteroflittle ASVS 4.0.1 and BSI C5 2020 are now available as requirement sets
